### ISSUE TITLE
Parcel interactions crash application

### ISSUE THREAD

**Issue by nickballen** [CityOfDetroit/parcel-viewer#11]
Searching or interacting with certain parcels cause the application to crash. This behavior happens across browsers (Firefox/Chrome/Safari) Some examples:

https://cityofdetroit.github.io/parcel-viewer/05004190.001
https://cityofdetroit.github.io/parcel-viewer/15003802.002L/
https://cityofdetroit.github.io/parcel-viewer/15009498-515/

One hunch is it might be related to overlay parcels: where a land parcel also has overlying, but separate, improvement parcels (i.e. special acts parcels). But I can't find a consistent pattern in parcel attributes that would cause this.

**Comment by jmcbroom** [comment]
Hey, thanks for the bug report. It looks like the issue is the value for `ZONING` on these three parcels is blank ` ` which is causing it to crash on lookup in the zoning dictionary

**Comment by nickballen** [comment]
Never a dull moment with the parcel data!
